### ISSUE TITLE
cant run upnp

### ISSUE THREAD

**Issue by minmaxdata** [nixops/homebrew-burstcoind#2] opened 2018-07-21 21:32 UTC
➜  work brew -v
Homebrew 1.7.0
Homebrew/homebrew-core (git revision e1689; last commit 2018-07-21)
➜  work java -version 
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
mac osx 10.13.6

[SEVERE] 2018-07-21 14:09:58 brs.peer.Peers - Can't start UPnP
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at org.bitlet.weupnp.GatewayDevice.simpleUPnPcommand(GatewayDevice.java:223)
	at org.bitlet.weupnp.GatewayDevice.addPortMapping(GatewayDevice.java:311)
	at brs.peer.Peers$Init.lambda$init$0(Peers.java:288)
	at java.lang.Thread.run(Thread.java:748)
[INFO] 2018-07-21 14:10:57 brs.statistics.StatisticsManagerImpl - handling 10.20 blocks/s account cache hit ratio now/total:83.13%/83.13%
[INFO] 2018-07-21 14:11:27 brs.peer.Peers - Finished connecting to 4 well known peers.
[INFO] 2018-07-21 14:11:27 brs.peer.Peers - You can open your Burst Wallet in your favorite browser with: http://127.0.0.1:8125 or http://localhost:8125
[INFO] 2018-07-21 14:11:45 brs.statistics.StatisticsManagerImpl - handling 10.20 blocks/s account cache hit ratio now/total:99.11%/97.51%
[INFO] 2018-07-21 14:12:24 brs.statistics.StatisticsManagerImpl - handling 13.16 blocks/s account cache hit ratio now/total:95.87%/97.33%
[INFO] 2018-07-21 14:13:02 brs.statistics.StatisticsManagerImpl - handling 12.82 blocks/s account cache hit ratio now/total:96.56%/97.24%
[INFO] 2018-07-21 14:13:47 brs.statistics.StatisticsManagerImpl - handling 11.36 blocks/s account cache hit ratio now/total:99.52%/98.08%
[INFO] 2018-07-21 14:14:34 brs.statistics.StatisticsManagerImpl - h

**Comment by MrPilotMan** [comment] 2018-07-21 23:10
This is an issue with your personal router settings.

**Comment by nixops** [comment] 2018-07-24 07:16
Is it possible for you to try from another location and verify it is your router blocking the upnp?

**Comment by nixops** [comment] 2018-07-25 06:13
Could you attempt to restart the daemon and post output? @minmaxdata

**Comment by nixops** [comment] 2018-08-04 16:06
Ok, @minmaxdata I will end up closing this in two days if no response, I hope burstcoind is working as intended :)

**Comment by nixops** [comment] 2018-08-07 06:04
Closing, please reopen if needed.

**Closed by nixops** 2018-08-07 06:04 UTC
